zh_CN:
  password:
    new-passoword-mismatch-repeated-password: 你的新密码与确认密码不符
    new-passoword-cannot-be-same-as-old-password: 你的新密码不能是旧密码
    must-between-8-32-characters-in-length: 你的新密码只能在8到32个字符之间
    must-have-more-than-3-unique-characters: 你的新密码必须包含三个以上的特殊字符
    too-simple: 你的新密码看上去太简单了
    old-password-incorrect: 你的旧密码有误
    _string: 密码
  profile: 玩家资料
  avatar: 头像
  avatar-description: 我们建议至少上传分辨率为 512x512 (或者长宽比为 1:1)的PNG或JPG图片.并且图片大小低于5MB
  choose-file: 选择一张图片
  save: 保存
  preview: 预览
  customisation: 个性化
  banner: 背景横幅
  banner-description: 建议上传分辨率为 1440x262 的 GIF, PNG, JPG, JPEG 等四种格式的图片
  profile-background: 资料背景
  profile-background-description: 建议上传长宽比为 16:9  的 PNG, JPG, JPEG 格式的图片
  password-change: 更改密码
  old-password: 旧密码
  new-password: 新密码
  repeat-password: 确认新密码
  user-information: 用户信息
  username: 你的用户名
  settings: 设置
  bad-image-extension: 你选择的%{something}必须是 .jpg .jpeg .png 这三种文件之一
  change-succeed: 你的 %{something}已经修改成功!
  no-image-was-selected: 请选择一张图片
